sudo: required
dist: trusty

#branches:
#  only:
#    - master
#    - /^\d\.\d+$/

# Tricks to avoid unnecessary cache updates
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache

language: scala

jdk:
  - oraclejdk8

script:
  - sbt -jvm-opts .travis.jvmopts test

after_success:
  - sbt -jvm-opts .travis.jvmopts publish

env:
  global:
  - secure: NBsul3m4SsWYReexW6p2NapNz5fVQv5jQe72iG6hdUCnmkzCIvB30H2IQJ5vpTzBM+jkQacxE8UwLH+eMttzaLNEfTadoQyYCiiCMf3wmhtNYyIYaNQCOk0jhn/Ybl0POIbVWGFEZfyVbV4hOeBpCs8pSfcjJ6WjXgyReTs1k0yqZagZ3jFXUkttbRorwS4vw004vZ53Q/ijQLn5KICM2ymkdIvth/a5sQPaKfT47DCMAiugGamx7KPLNwaN8hn20+bJcrJAngtQdt0EQsK4ZYt6Gf5BFpfOtCi7iGUgPDlZZaYRheBWWkgJc19jCGNjOVDN+3bKLYo1/X1O/ZgyLJnHn0zuHDg3LFLkeej4Tuxd6CP/m3FYQ8wt0oivpOKyh4YHiGJCNqP38kFk4ta9SJnXwE4HyYaCmz8BJoVhqJT5F3Gc6VsCGibw4hswueQ2/QJwxd1Ix7ZQFi7H4WF9tnyz+qE1y6XJwTrVBDC8U2Uhz7yuLAi5U7rP6d9Y+ut9ZLFAv3RoxDTkMRi60ZwtORS9anfnYP/G+NUaf31g9lbVMu3lV1xYjcDTmen48rR0pCwgQIyx7sbU/vYrZDQRV+ZKrQ2/ji7hzHsui3OxEiWo4Taj69OfhsW50Kwk1ieOdjbH2/Ul00IfvbmZzJmEzQnshHwLEug1xxdfvxrgdgs=
  - secure: Pu+T5rR/l1i5XJQC7rxlgfVdXLrvFgXc9kv8tTAA9rc6B7gLyV7VMg/OMa6kfxOzXvluG39q/CXWgcSzAEt+c1mu0lgZyfIlotwiGExcsH3tCjUg5cMjnV5kOFYz5GgFidcux8cDTWilVqdf3ieqyKh/ERqu6ZvYCo01FC76MIfIZJBjJtwa7a5DhFBj8GDmjbDB/9J9hqen+8hJo4eMUPJ15+zPqvEouQq0gPRx52Dj04kr6Xpyf2FdUnOUpU7K40+KXhdZSdLeXdIYFJqzUNnQjkAZTTwAyRDR+5N4XJn+kDnFhEMfFge54AEiiYfoKs0JOsjVC1beRyzlHsLWza5OJmtewvhoJ6sjX5/Bxdj2HpfmFX0pXUjY//D6Q0RHGeYwwGKM+PbxW2OJxNzmPQHPeZVCwB/UohWFgCbN1OdG/Kex18/jwfagPB/hmpgcAE1fhIKGY+7UOlkbcJu/vZaknNFHKL4LcIrr7oWli4SRfnncPyfqmXu0uEQVIYXD3usb9+9YF4cf5RVrzC+I3NkFSfcyWNJrFA5FeIKBemfevp2o9u+yRxMx/rYleVMOSQgw0+Wq3kKZOtsQu+2LPLCoWo9qpYr6uKLMCQn8OqnEgHggB9M796iewEP+RdgfDvuu+ys0Kzu9t3/lwXsmqVSNLhWyZnvNz/qKtV1R0Do=


